version: '3'
services:  
  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: ${DB_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
